AiCam.begin(SerialPin.P2, SerialPin.P8, 9600)
let val = AiCam.qr()
basic.pause(50)
serial.redirectToUSB()
serial.setBaudRate(BaudRate.BaudRate9600)
serial.writeString(val)
basic.pause(50)
basic.forever(function () {
    AiCam.begin(SerialPin.P2, SerialPin.P8, 9600)
    AiCam.setMode(AiCam.Mode.QR)
})
